[genai]
api_key = "AIzaSyCSzYmBgaAxS-W1W9IxzM9LjkLRaZuty4U"
billing_account_id="billingAccounts/014FB5-C78E58-7E336C"
#billing_account_id = "billingAccounts/110824830494860116019"
# No service_account_file_path needed; uses ADC/WIF with SSO as per your constraints
